# Generated by Django 5.1.3 on 2024-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_participation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='player', max_length=10),
        ),
    ]
